# Generated by Django 3.0.14 on 2022-10-17 15:24

import apps.scrapper.models
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_data', jsonfield.fields.JSONField(default=apps.scrapper.models.default_urls)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.City')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.Language')),
            ],
            options={
                'unique_together': {('city', 'language')},
            },
        ),
    ]
