# Generated by Django 3.0.14 on 2022-10-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
    ]
